### Pandas Advanced Practice Test
Dataset: `../data/titanic.csv`

**Instructions:**
Write the exact Pandas implementations for each task. The instructions only state the final objective. No step-by-step guidance is provided.

In [1]:
import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv('../data/titanic.csv')
display(df.head())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
# Write your code here
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

#### Task 3: Unique Values & Value Counts (Easy)
Find the total number of unique values for every single column in the dataset. Then, display the raw exact count of how many passengers survived (`Survived` column) and how many passengers were in each ticket class (`Pclass` column).

In [3]:
# Write your code here
display(df.nunique())
display(df['Survived'].value_counts())
display(df['Pclass'].value_counts())
# display(df.groupby('Survived').count())
# display(df.groupby('Pclass').count())

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

Survived
0    549
1    342
Name: count, dtype: int64

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

#### Task 2: Missing Values & Duplicates Check (Easy)
Calculate and print the total number of missing (`NaN`) values for each column in the dataset. Next, calculate and print the total number of duplicated rows in the entire DataFrame.

In [4]:
# Write your code here
display(df.isna().sum())
display(df.duplicated().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

np.int64(0)

#### Task 1: Basic DataFrame Info & Summary (Easy)
Use Pandas built-in functions to display the technical information (data types, memory usage) of the DataFrame. Then, display the statistical summary (mean, std, min, max, etc.) specifically for all numerical columns.

In [5]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

#### Task 4: Basic Slicing & Correlation (Easy)
Display the first 7 rows and the last 3 rows of the DataFrame. After that, calculate and display the correlation matrix, but only for the numeric columns in the dataset.

In [9]:
# Write your code here
# display(df.head(7))
display(df.iloc[:7])
# display(df.tail(3))
display(df.iloc[-3:])
# display(df[['PassengerId','Survived', 'Pclass', 'Age','SibSp','Parch','Fare']].corr())
display(df.select_dtypes(include='number').corr())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
PassengerId,1.000000,-0.005007,-0.035144,0.036847,-0.057527,-0.001652,0.012658
Survived,-0.005007,1.000000,-0.338481,-0.077221,-0.035322,0.081629,0.257307
Pclass,-0.035144,-0.338481,1.000000,-0.369226,0.083081,0.018443,-0.549500
Age,0.036847,-0.077221,-0.369226,1.000000,-0.308247,-0.189119,0.096067
SibSp,-0.057527,-0.035322,0.083081,-0.308247,1.000000,0.414838,0.159651
Parch,-0.001652,0.081629,0.018443,-0.189119,0.414838,1.000000,0.216225
Fare,0.012658,0.257307,-0.549500,0.096067,0.159651,0.216225,1.000000

#### Task 5: Label Encoding (Competition Style - Medium)
Create mapping dictionaries to convert categorical text features into integer arrays for the model. 
Map the `Sex` column (`'male'` to `1`, `'female'` to `0`) and the `Embarked` column (`'S'` to `0`, `'C'` to `1`, `'Q'` to `2`). Apply these mappings to modify the columns in the DataFrame directly.

In [7]:
# Write your code here
label_sex = { 'male' : 1, 'female' : 0 }
label_embarked = { 'S' : 0, 'C' : 1, 'Q' : 2 }
# print(df['Sex'].unique())
df['Sex'] = df['Sex'].map(label_sex)
# print(df['Embarked'].unique())
df['Embarked'] = df['Embarked'].map(label_embarked)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,0.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,1.0
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,0.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,0.0
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",1,27.0,0,0,211536,13.0000,NaN,0.0
887,888,1,1,"Graham, Miss. Margaret Edith",0,19.0,0,0,112053,30.0000,B42,0.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",0,NaN,1,2,W./C. 6607,23.4500,NaN,0.0
889,890,1,1,"Behr, Mr. Karl Howell",1,26.0,0,0,111369,30.0000,C148,1.0
890,891,0,3,"Dooley, Mr. Patrick",1,32.0,0,0,370376,7.7500,NaN,2.0

#### Task 6: String Manipulation & Text Truncation (Competition Style - Medium)
Using Pandas string accessors, create a new column named `Short_Name` that takes the original `Name` column, converts it entirely to lowercase, splits the text into words, and keeps **only the first two words** of the name. Join them back as a string.

In [ ]:
# Write your code here
def process(text:str):
    text = text.lower()
    text = text.split()
    text = text[:2]
    text = ' '.join(text)
    return text
# df['Short_Name'] = df['Name'].str.lower().str.split().str[:2].str.join(' ')
df['Short_Name'] = df['Name'].apply(process)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Short_Name
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,0.0,"braund, mr."
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,1.0,"cumings, mrs."
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,0.0,"heikkinen, miss."
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,0.0,"futrelle, mrs."
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,NaN,0.0,"allen, mr."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",1,27.0,0,0,211536,13.0000,NaN,0.0,"montvila, rev."
887,888,1,1,"Graham, Miss. Margaret Edith",0,19.0,0,0,112053,30.0000,B42,0.0,"graham, miss."
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",0,NaN,1,2,W./C. 6607,23.4500,NaN,0.0,"johnston, miss."
889,890,1,1,"Behr, Mr. Karl Howell",1,26.0,0,0,111369,30.0000,C148,1.0,"behr, mr."
890,891,0,3,"Dooley, Mr. Patrick",1,32.0,0,0,370376,7.7500,NaN,2.0,"dooley, mr."

#### Task 7: Text Extraction & Feature Engineering (Medium)
Extract the passenger's title (e.g., 'Mr', 'Mrs', 'Miss', 'Master') from the `Name` column using regular expressions and store it in a new column called `Title`. Then, replace all rarely occurring titles (anything other than Mr, Mrs, Miss, Master) with a single string value `'Rare'`.

In [11]:
# Write your code here
df['Title'] = df['Name'].str.extract(r' ([A-Za-z]+)\.')
main_titles = ['Mr', 'Mrs', 'Miss', 'Master']
df['Title'] = df['Title'].apply(lambda x: x if x in main_titles else 'Rare')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Rare
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Miss
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Miss
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Mr
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Mr

#### Task 8: Multi-level Aggregation (Medium)
Calculate the **survival rate** (mean of `Survived` column) and the **average fare paid** (mean of `Fare`), grouped by both `Pclass` and `Embarked`. Return the result as a new DataFrame sorted by survival rate in descending order.

In [ ]:
# Write your code here
mean_survived = df['Survived'].mean()
mean_fare = df['Fare'].mean()
display(df.groupby(['Pclass', 'Embarked'])[['Survived', 'Fare']].mean().sort_values(by='Survived', ascending=False))
print(mean_survived)
print(mean_fare)

0.3838383838383838
32.204207968574636

#### Task 9: Pivot Tables (Medium)
Create a pivot table with `Pclass` as the index (rows), `Sex` as the columns, and the values representing the **median `Age`** of ONLY the passengers who `Survived` (where `Survived == 1`).

In [15]:
# Write your code here
display(df[df['Survived'] == 1].pivot_table(index='Pclass', columns='Sex', values='Age', aggfunc='median'))

Sex     female  male
Pclass
1         35.0  36.0
2         28.0   3.0
3         19.0  25.0

#### Task 10: Contextual Missing Value Imputation (Medium-Hard)
Fill the missing values in the `Age` column by using the median age of passengers sharing the exact same `Pclass` and `Sex`. After that, drop any rows that have missing values in the `Embarked` column.

In [ ]:
# Write your code here
print(df.isna().sum())
median_age = df["Age"].median()
df['Age'] = df['Age'].fillna(df.groupby(['Pclass', 'Sex'])['Age'].transform('median'))
df = df.dropna(subset=['Embarked'])
print(df.isna().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
Short_Name       0
dtype: int64
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
Short_Name       0
dtype: int64

#### Task 11: Advanced Conditional Slicing (Medium-Hard)
Filter the DataFrame to find the names of all passengers meeting **all** the following criteria:
1. Female (`Sex == 'female'`)
2. In 1st class (`Pclass == 1`)
3. Under 30 years old (`Age < 30`)
4. Paid a `Fare` strictly greater than the 75th percentile of all 1st class fares.

Output only the `Name` column.

In [29]:
def list_func(func, search=None):
    if search:
        list_result = [f for f in dir(func) if search.lower() in f.lower()]
    else:
        list_result = [f for f in dir(func)]
    print(list_result)
# Write your code here
fare_75 = df[df['Pclass']==1]['Fare'].quantile(0.75)
df[(df['Sex']=='female')&(df['Pclass']==1)&(df['Age']<30)&(df['Fare']>fare_75)]['Name']

88                            Fortune, Miss. Mabel Helen
297                         Allison, Miss. Helen Loraine
307    Penasco y Castellana, Mrs. Victor de Satode (M...
311                           Ryerson, Miss. Emily Borie
341                       Fortune, Miss. Alice Elizabeth
393                               Newell, Miss. Marjorie
435                            Carter, Miss. Lucile Polk
498      Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
689                    Madill, Miss. Georgette Alexandra
700    Astor, Mrs. John Jacob (Madeleine Talmadge Force)
708                                 Cleaver, Miss. Alice
730                        Allen, Miss. Elisabeth Walton
742                Ryerson, Miss. Susan Parker "Suzette"
Name: Name, dtype: object

#### Task 12: Class Balancing & Downsampling (Competition Style - Hard)
Determine the number of passengers who survived and who did not survive. Find the minimum count between these two classes. Then, downsample the majority class so that the DataFrame contains an exactly equal number of rows for both `Survived = 0` and `Survived = 1`.

In [ ]:
# Write your code here
count = df.groupby('Survived').count()
min = count.min().iloc[0]
min

df = df.drop('Cabin', axis='columns')
df = df.groupby('Survived', group_keys=False).apply(lambda x : x.sample(n=min, random_state=42))
df.groupby('Survived').count()

C:\Users\Dindin\AppData\Local\Temp\ipykernel_17632\3510123801.py:7: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df = df.groupby('Survived', group_keys=False).apply(lambda x : x.sample(n=min, random_state=42))

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Short_Name
Survived,,,,,,,,,,,
0,340,340,340,340,340,340,340,340,340,340,340
1,340,340,340,340,340,340,340,340,340,340,340

In [ ]:
df = df.reset_index(drop=True)
df.to_csv('../data/titanic_down.csv')

#### Task 13: Stratified Splitting & Concatenation (Competition Style - Hard)
Use `train_test_split` from `sklearn.model_selection` to divide your dataframe into `train_df` (80%) and `valid_df` (20%). Crucially, ensure the split is **stratified** based on the `Survived` label. Once split, use `pd.concat` to merge `train_df` and `valid_df` back together row-wise into a new dataframe called `combined_df`.

In [ ]:
# Write your code here
from sklearn.model_selection import train_test_split

df = pd.read_csv('../data/titanic_down.csv')
print(df.shape)
fare_75 = df[df['Pclass'] == 1]['Fare'].quantile(0.75)
filtered = df[(df['Sex'] == 'female') & (df['Pclass'] == 1) & (df['Age'] < 30) & (df['Fare'] > fare_75)]
display(filtered['Name'])

(680, 13)
(544, 13)
(136, 13)