In [1]:
def list_func(func, search=None):
    if search:
        func_list = [f for f in dir(func) if search.lower() in f.lower()]
    else:
        func_list = [f for f in dir(func)]
    print(func_list)

In [2]:
import pandas as pd
import numpy as np

In [3]:
root_path = './data'
column=['target', 'ids', 'date', 'flag', 'user', 'text']
df = pd.read_csv(root_path + '/sentiment140.csv', names=column, encoding='latin-1')
df

,target,ids,date,flag,user,text
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
...,...,...,...,...,...,...
1599995,4,2193601966,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,AmandaMarie1028,Just woke up. Having no school is the best fee...
1599996,4,2193601969,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,TheWDBoards,TheWDB.com - Very cool to hear old Walt interv...
1599997,4,2193601991,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,bpbabe,Are you ready for your MoJo Makeover? Ask me f...
1599998,4,2193602064,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,tinydiamondz,Happy 38th Birthday to my boo of alll time!!! ...
1599999,4,2193602129,Tue Jun 16 08:40:50 PDT 2009,NO_QUERY,RyanTrevMorris,happy #charitytuesday @theNSPCC @SparksCharity...

In [4]:
df.head(3)

,target,ids,date,flag,user,text
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...

In [5]:
df.tail(3)

,target,ids,date,flag,user,text
1599997,4,2193601991,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,bpbabe,Are you ready for your MoJo Makeover? Ask me f...
1599998,4,2193602064,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,tinydiamondz,Happy 38th Birthday to my boo of alll time!!! ...
1599999,4,2193602129,Tue Jun 16 08:40:50 PDT 2009,NO_QUERY,RyanTrevMorris,happy #charitytuesday @theNSPCC @SparksCharity...

In [6]:
df.describe()

             target           ids
count  1.600000e+06  1.600000e+06
mean   2.000000e+00  1.998818e+09
std    2.000001e+00  1.935761e+08
min    0.000000e+00  1.467810e+09
25%    0.000000e+00  1.956916e+09
50%    2.000000e+00  2.002102e+09
75%    4.000000e+00  2.177059e+09
max    4.000000e+00  2.329206e+09

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1600000 entries, 0 to 1599999
Data columns (total 6 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   target  1600000 non-null  int64
 1   ids     1600000 non-null  int64
 2   date    1600000 non-null  object
 3   flag    1600000 non-null  object
 4   user    1600000 non-null  object
 5   text    1600000 non-null  object
dtypes: int64(2), object(4)
memory usage: 73.2+ MB

In [8]:
row, col = df.shape
print(f"row : {row}, column : {col}")

row : 1600000, column : 6

In [9]:
df.isna().sum()

target    0
ids       0
date      0
flag      0
user      0
text      0
dtype: int64

In [10]:
df.dropna()

,target,ids,date,flag,user,text
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
...,...,...,...,...,...,...
1599995,4,2193601966,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,AmandaMarie1028,Just woke up. Having no school is the best fee...
1599996,4,2193601969,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,TheWDBoards,TheWDB.com - Very cool to hear old Walt interv...
1599997,4,2193601991,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,bpbabe,Are you ready for your MoJo Makeover? Ask me f...
1599998,4,2193602064,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,tinydiamondz,Happy 38th Birthday to my boo of alll time!!! ...
1599999,4,2193602129,Tue Jun 16 08:40:50 PDT 2009,NO_QUERY,RyanTrevMorris,happy #charitytuesday @theNSPCC @SparksCharity...

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.drop_duplicates()

,target,ids,date,flag,user,text
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
...,...,...,...,...,...,...
1599995,4,2193601966,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,AmandaMarie1028,Just woke up. Having no school is the best fee...
1599996,4,2193601969,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,TheWDBoards,TheWDB.com - Very cool to hear old Walt interv...
1599997,4,2193601991,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,bpbabe,Are you ready for your MoJo Makeover? Ask me f...
1599998,4,2193602064,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,tinydiamondz,Happy 38th Birthday to my boo of alll time!!! ...
1599999,4,2193602129,Tue Jun 16 08:40:50 PDT 2009,NO_QUERY,RyanTrevMorris,happy #charitytuesday @theNSPCC @SparksCharity...

In [13]:
df['target'].value_counts()

target
0    800000
4    800000
Name: count, dtype: int64

In [14]:
df.groupby('target').count()

           ids    date    flag    user    text
target
0       800000  800000  800000  800000  800000
4       800000  800000  800000  800000  800000

In [15]:
df.columns

Index(['target', 'ids', 'date', 'flag', 'user', 'text'], dtype='object')

In [16]:
def preprocess_text(text:str, max_lenght:int=150):
    text = text.split()
    text = text[:max_lenght]
    text = ' '.join(text)
    text = text.lower()
    return text

In [17]:
df['text'] = df['text'].apply(lambda x : preprocess_text(x))
df['text']

0          @switchfoot http://twitpic.com/2y1zl - awww, t...
1          is upset that he can't update his facebook by ...
2          @kenichan i dived many times for the ball. man...
3             my whole body feels itchy and like its on fire
4          @nationwideclass no, it's not behaving at all....
                                 ...
1599995    just woke up. having no school is the best fee...
1599996    thewdb.com - very cool to hear old walt interv...
1599997    are you ready for your mojo makeover? ask me f...
1599998    happy 38th birthday to my boo of alll time!!! ...
1599999    happy #charitytuesday @thenspcc @sparkscharity...
Name: text, Length: 1600000, dtype: object

In [18]:
df['word_count'] = df['text'].str.split().str.len()
df

,target,ids,date,flag,user,text,word_count
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - awww, t...",19
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his facebook by ...,21
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@kenichan i dived many times for the ball. man...,18
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire,10
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all....",21
...,...,...,...,...,...,...,...
1599995,4,2193601966,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,AmandaMarie1028,just woke up. having no school is the best fee...,11
1599996,4,2193601969,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,TheWDBoards,thewdb.com - very cool to hear old walt interv...,11
1599997,4,2193601991,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,bpbabe,are you ready for your mojo makeover? ask me f...,11
1599998,4,2193602064,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,tinydiamondz,happy 38th birthday to my boo of alll time!!! ...,12
1599999,4,2193602129,Tue Jun 16 08:40:50 PDT 2009,NO_QUERY,RyanTrevMorris,happy #charitytuesday @thenspcc @sparkscharity...,5

In [19]:
sentiment_map = {0 : 'negative', 2 : 'neutral', 4 : 'positive'}
df['sentiment_label'] = df['target'].map(sentiment_map)
df[['sentiment_label', 'target']]

        sentiment_label  target
0              negative       0
1              negative       0
2              negative       0
3              negative       0
4              negative       0
...                 ...     ...
1599995        positive       4
1599996        positive       4
1599997        positive       4
1599998        positive       4
1599999        positive       4

[1600000 rows x 2 columns]

In [22]:
df['sentiment_label'].unique()

array(['negative', 'positive'], dtype=object)

In [29]:
df.iloc[-2:, :3]

         target         ids                          date
1599998       4  2193602064  Tue Jun 16 08:40:49 PDT 2009
1599999       4  2193602129  Tue Jun 16 08:40:50 PDT 2009

In [31]:
df[df['target']== 0].shape

(800000, 8)

In [34]:
df['combined_text'] = df['user'] + " says: " + df['text']
df.head()

,target,ids,date,flag,user,text,word_count,sentiment_label,combined_text
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - awww, t...",19,negative,_TheSpecialOne_ says: @switchfoot http://twitp...
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his facebook by ...,21,negative,scotthamilton says: is upset that he can't upd...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@kenichan i dived many times for the ball. man...,18,negative,mattycus says: @kenichan i dived many times fo...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire,10,negative,ElleCTF says: my whole body feels itchy and li...
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all....",21,negative,"Karoli says: @nationwideclass no, it's not beh..."

In [54]:
labels_count = df.groupby('sentiment_label').count()
min = labels_count.min().iloc[2]

labels_count

,target,ids,date,flag,user,text,word_count,combined_text
sentiment_label,,,,,,,,
negative,800000,800000,800000,800000,800000,800000,800000,800000
positive,800000,800000,800000,800000,800000,800000,800000,800000

In [59]:
df_downsampled = df.groupby('target').apply(lambda x : x.sample(n=min, random_state=42))
df_downsampled = df_downsampled.reset_index(drop=True)
df_downsampled

C:\Users\Dindin\AppData\Local\Temp\ipykernel_12600\1838608329.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_downsampled = df.groupby('target').apply(lambda x : x.sample(n=min, random_state=42))

,target,ids,date,flag,user,text,word_count,sentiment_label,combined_text
0,0,1974671194,Sat May 30 13:36:31 PDT 2009,NO_QUERY,simba98,@xnausikaax oh no! where did u order from? tha...,10,negative,simba98 says: @xnausikaax oh no! where did u o...
1,0,1997882236,Mon Jun 01 17:37:11 PDT 2009,NO_QUERY,Seve76,a great hard training weekend is over. a coupl...,25,negative,Seve76 says: a great hard training weekend is ...
2,0,2177756662,Mon Jun 15 06:39:05 PDT 2009,NO_QUERY,x__claireyy__x,"right, off to work only 5 hours to go until i'...",13,negative,"x__claireyy__x says: right, off to work only 5..."
3,0,2216838047,Wed Jun 17 20:02:12 PDT 2009,NO_QUERY,Balasi,i am craving for japanese food,6,negative,Balasi says: i am craving for japanese food
4,0,1880666283,Fri May 22 02:03:31 PDT 2009,NO_QUERY,djrickdawson,jean michel jarre concert tomorrow gotta work ...,10,negative,djrickdawson says: jean michel jarre concert t...
...,...,...,...,...,...,...,...,...,...
1599995,4,1963116716,Fri May 29 12:13:43 PDT 2009,NO_QUERY,xx1n1xx,yay for atwin who had her baby boy matthew joh...,16,positive,xx1n1xx says: yay for atwin who had her baby b...
1599996,4,1979880815,Sun May 31 04:52:47 PDT 2009,NO_QUERY,joanne7964,@eva_abreu maybe we're bored..lol..i got plent...,19,positive,joanne7964 says: @eva_abreu maybe we're bored....
1599997,4,1770953638,Mon May 11 22:43:54 PDT 2009,NO_QUERY,maxiiieee,@ashlili like meeeeeeeee,3,positive,maxiiieee says: @ashlili like meeeeeeeee
1599998,4,2065164963,Sun Jun 07 08:02:01 PDT 2009,NO_QUERY,pinkgeekstudios,okay off to sleep now,5,positive,pinkgeekstudios says: okay off to sleep now
1599999,4,1754307909,Sun May 10 05:48:31 PDT 2009,NO_QUERY,djmisskai,"@v_j i haven't been sleeping well this wk, had...",30,positive,djmisskai says: @v_j i haven't been sleeping w...